name: terraform-plan

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: Deploy to
        options:
        - dev
        required: true
        default: 'dev'
jobs:
  plan:
    name: plan terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://app-cicd/hello-world/secret

      - name: Print masked secret
        run: 'echo "Secret: $SECRET"'
        # Prints: Secret: ***
      - name: Initialize Terraform
      - name: Plan terraform
        run: |
         OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
